#!/bin/bash

canonpath() {
    [[ -d "$1" ]] && {
        ( # Arg is a dir, so cd into it and pwd -P
            builtin cd -L -- "$1" \
             &&  command pwd -P
        ) && return
        # We failed to cd or pwd!
        echo "$1"; false
        return
    }
    # Arg is not a dir
    (
        cd -L -- "$(dirname -- $0)"; echo "$(pwd -P)/$(basename -- $0)" )
}
