#!/bin/bash
# shellkit/shellkit_setup_base
# Source this.

[[ -z $Scriptdir ]] && die "\$Scriptdir not defined"
read Kitname _ < "${Scriptdir}/../Kitname"
[[ -z $Kitname ]] && die "\$Kitname not defined"

inode() {
    # Returns inode of $1
    ( command ls -i "$1" | command awk '{print $1}') 2>/dev/null
}

is_on_path() {
    # Return true if $1 is on the PATH
    local tgt_dir="$1"
    [[ -z $tgt_dir ]] && { true; return; }
    local vv=( $(echo "${PATH}" | tr ':' '\n') )
    for v in "${vv[@]}"; do
        if [[ $tgt_dir == "$v" ]]; then
            return
        fi
    done
    false
}

path_fixup_local_bin() {
    # Add ~/.local/bin to the PATH if it's not already.  Modify
    # either .bash_profile or .profile honoring bash startup rules.
    local kitname="${1}"
    [[ -z $kitname ]] && kitname="shellkit"
    (
        builtin cd
        semaphore=.local/bin/_semaphore_$$
        echo "#!/bin/sh" $'\n' "true" > "${semaphore}"
        command chmod +x "${semaphore}"
        if ! command bash -l -c "cd; ${semaphore}"; then
            exit 1  # .local/bin is not on the PATH
        fi
        rm ${semaphore}
        true
    ) && { true; return; }
    (
        local profile=.bash_profile
        [[ -f $profile ]] || profile=.profile
        tmp_profile="profile-tmp.$$"
        echo "export PATH=\${HOME}/.local/bin:\$PATH # Added by ${kitname}" > "${tmp_profile}" || die 202
        [[ -e $profile ]] && cat $profile >> "${tmp_profile}"
        mv $tmp_profile $profile || die 203
        echo "WARNING: ~/.local/bin was added to your PATH by modifying ${PWD}/${profile}.  It is up to you to ensure that the contents of ~/.local/bin are benign!" >&2
    )

    reload_reqd=true
}

shrc_fixup() {
    # We must ensure that .bashrc sources our ps1-foo.bashrc script
    (
        # Each kit defines a [Kitname]-semaphore function which just prints '1'
        /bin/bash -l -c "type -f ${Kitname}-semaphore >/dev/null"
    ) &>/dev/null && {
        return
    }

    ( # Add hook to .bashrc
        echo "[[ -n \$PS1 && -f \${HOME}/.local/bin/${Kitname}/${Kitname}.bashrc ]] && source \${HOME}/.local/bin/${Kitname}/${Kitname}.bashrc # Added by ${Kitname}-setup.sh"
        echo
    ) >> ${HOME}/.bashrc

    reload_reqd=true
}

